server.port=8085

bot.name=DedushkinPogreb_bot
bot.token=7800365762:AAEFJsIkhgAXEQX1IRNjEMZ9HDZvfqAYwE8

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
#sring.rabbitmq.username=userok
#spring.rabbitmq.password=1234
spring.rabbitmq.queues.text-message-update= text_message_update
spring.rabbitmq.queues.doc-message-update= doc_message_update
spring.rabbitmq.queues.photo-message-update= photo_message_update
spring.rabbitmq.queues.answer-message= answer_message

#db related settings
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

