server.port=8084


bot.token = 7800365762:AAEFJsIkhgAXEQX1IRNjEMZ9HDZvfqAYwE8
bot.name = DedushkinPogreb_bot

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=userok
spring.rabbitmq.password=1234