server.port=8084

bot.name=DedushkinPogreb_bot
bot.token=7800365762:AAEFJsIkhgAXEQX1IRNjEMZ9HDZvfqAYwE8
bot.uri= https://78c9-2405-4802-80f2-6b00-9c0a-1f7b-a88f-19c9.ngrok-free.app

server.ssl.enabled=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
#sring.rabbitmq.username= userok
#spring.rabbitmq.password= 1234

spring.rabbitmq.queues.text-message-update= text_message_update
spring.rabbitmq.queues.doc-message-update= doc_message_update
spring.rabbitmq.queues.photo-message-update= photo_message_update
spring.rabbitmq.queues.answer-message= answer_message
